---
title: "Threshold Return Level Exceedances"
author: "Samuel McDonnell"
date: "2024-04-25"
output: html_document
---

```{r}
library(sf)
library(ggplot2)
library(dplyr)
library(tmap)
library(tidyr)

data <- readRDS("gtsr_daily_max_1979_2014.rds")
```


```{r}
library(extRemes)

# Compute the 99th percentile threshold
threshold_99 <- quantile(dun_laoghaire$surge_daily_max, probs = 0.95)

# Filter the data to include only values above the 99th percentile threshold
dun_laoghaire_above_threshold <- dun_laoghaire[dun_laoghaire$surge_daily_max > threshold_99, ]

# Fit GEV distribution to threshold exceedances
gev_threshold_fit <- fevd(dun_laoghaire_above_threshold$surge_daily_max, threshold = threshold_99, method = "MLE", type = "GP")

# Estimate return levels
return_levels <- return.level(gev_threshold_fit, return.period = c(5, 20, 100), do.ci = TRUE)

plot(gev_threshold_fit)

# Print return levels
print(return_levels)



```
## Extremes analysis threshold

```{r, messages = FALSE}
# Define function to estimate return levels using threshold exceedance approach
estimate_return_levels_threshold <- function(station_data_threshold, threshold) {
  # Subset the exceedances over the threshold
  threshold_exceedances <- station_data_threshold$surge_daily_max[station_data_threshold$surge_daily_max > threshold]
  # Fit GPD distribution to threshold exceedances
  threshold_fit <- fevd(threshold_exceedances, threshold = threshold, type = "GP")
  # Estimate return levels
  return_levels_threshold <- return.level(threshold_fit, return.period = c(5, 20, 100))
  
  # Return the return levels
  return(return_levels_threshold)
}

# Create an empty dataframe to store return level estimates for all stations using threshold approach
return_levels_all_threshold <- data.frame(station_name = character(),
                                          return_5yr = numeric(),
                                          return_20yr = numeric(), 
                                          return_100yr = numeric(),
                                          stringsAsFactors = FALSE)

# Loop through each station
for (i in 1:nlevels(data$station_name)) {
  # Subset data for the current station
  station_data_threshold <- data %>% filter(station_name == levels(data$station_name)[i])
  
  # Calculate the threshold (adjust the percentile as needed)
  threshold <- quantile(station_data_threshold$surge_daily_max, probs = 0.95)
  
  # Estimate return levels for the current station using threshold exceedance approach
  return_levels_threshold <- estimate_return_levels_threshold(station_data_threshold, threshold)
  
  # Add return levels to the dataframe
  return_levels_all_threshold <- rbind(return_levels_all_threshold,
                                       data.frame(station_name = levels(data$station_name)[i],
                                                  return_5yr = return_levels_threshold[1],
                                                  return_20yr = return_levels_threshold[2],
                                                  return_100yr = return_levels_threshold[3]))
}

# Print return levels for station "795" (Dun Laoghaire)
print(return_levels_all_threshold %>% filter(station_name == "795")) # check DL :)

```

ABOVE SEEMS CORRECT, NOW MAP AND PLOT EXCEEDANCES

## Map the return levels 

```{r}

#Load spatial data
ireland <- st_read("IRL_adm0.shp")


data_unique <- distinct(data, station_name, lon, lat)

## switched to use inner join to join the datasets
return_levels_with_coords_threshold <- inner_join(return_levels_all_threshold, data_unique, by = "station_name")

# Convert return_levels_all_with_coords to sf object
return_levels_sf_threshold <- st_as_sf(return_levels_with_coords_threshold, coords = c("lon", "lat"), crs = 4326)

# Plot map of Ireland with return levels represented by colors
tm_shape(ireland) +
  tm_borders() +
  tm_shape(return_levels_sf_threshold) +
  tm_dots(col = "return_5yr", size = 1, alpha = 0.5, title = "Return Level (5yr) Using Threshold Method") +
  tm_style("gray")


# Plot map of Ireland with return levels represented by colors
tm_shape(ireland) +
  tm_borders() +
  tm_shape(return_levels_sf_threshold) +
  tm_dots(col = "return_20yr", size = 1, alpha = 0.5, title = "Return Level (20yr) Using Threshold Method") +
  tm_style("gray")

# Plot map of Ireland with return levels represented by colors
tm_shape(ireland) +
  tm_borders() +
  tm_shape(return_levels_sf_threshold) +
  tm_dots(col = "return_100yr", size = 0.5, alpha = 0.5, title = "Return Level (100yr) Using Threshold Method") +
  tm_style("gray")
```

Annual exceedances of 5yr return level


```{r}

exceedance_data <-inner_join(data %>% select(station_name, year, month, day, surge_daily_max), return_levels_with_coords_threshold, by = "station_name")

annual_exceedance_counts <- exceedance_data %>% 
                              group_by(station_name, year) %>% 
                              summarise(exceedance_5yr = sum(surge_daily_max > return_5yr),
                                        exceedance_20yr = sum(surge_daily_max > return_20yr)) %>% 
                              ungroup()

## plot for DL 
ggplot(annual_exceedance_counts %>% filter(station_name == "795"), aes(x = year, y = exceedance_5yr)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Exceedances Above 5-Year Return Level Per Year (Station 795)",
       x = "Year", y = "Exceedances")

```

```{r}
exceedance_data  <- exceedance_data %>%
  distinct(station_name, lon, lat) %>%
  mutate(coast = case_when(
    lon < -7 & lat > 54 ~ "North West",
    lon < -9 & lat <= 54 ~ "South West",
    lon > -6.5 & lat > 52.3 ~ "Central East",
    TRUE ~ "South East"
  )) %>%
  arrange(coast, lat)  # Order stations by coast and latitude


# Plot the heatmap with adjusted x-axis labels
heatmap_plot <- ggplot(annual_exceedance_counts, aes(x = year, y = station_name, fill = exceedance_5yr)) +
  geom_tile() +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(title = "Exceedances Above 5-Year Return Level Heatmap",
       x = "Year", y = "Station", fill = "Exceedances") +
  theme(axis.text.y = element_text(size =1),  # Adjust y-axis text size
        axis.text.x = element_text(angle = 45, size = 7),  # Rotate and adjust x-axis text size
        plot.title = element_text(size = 12),  # Adjust title size
        plot.margin = margin(t = 2, r = 2, b = 2, l = 2, unit = "cm")) +  # Adjust plot margins
  scale_y_discrete(limits = exceedance_data$station_name, labels = exceedance_data$coast) +
  scale_x_continuous(breaks = unique(annual_exceedance_counts$year)) +  # Group and order stations by coast
  theme(plot.background = element_rect(fill = "white", color = "black", linewidth = 0.5),
        panel.background = element_rect(fill = "white", color = "black", linewidth = 0.5),
        plot.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(color = "black"))

# Print the plot
print(heatmap_plot)
```



```{r}
# Filter points for each group
north_west_points <- unique_coords_sf %>%
  filter(st_coordinates(geometry)[, "X"] < -7 & st_coordinates(geometry)[, "Y"] > 54)

south_west_points <- unique_coords_sf %>%
  filter(st_coordinates(geometry)[, "X"] < -9 & st_coordinates(geometry)[, "Y"] <= 54)

central_east_points <- unique_coords_sf %>%
  filter(st_coordinates(geometry)[, "X"] > -6.5 & st_coordinates(geometry)[, "Y"] > 52.3)

south_east_points <- unique_coords_sf %>%
  filter(st_coordinates(geometry)[, "X"] >= -9 & st_coordinates(geometry)[, "Y"] <= 52.3)

# Plot the map for each group
tm_shape(ireland) +  
  tm_borders() +      
  tm_shape(north_west_points) +  
  tm_dots(col = "blue", size = 0.5, title = "North West Points") +
 
  tm_shape(south_west_points) +  
  tm_dots(col = "red", size = 0.5, title = "South West Points") +

  tm_shape(central_east_points) +  
  tm_dots(col = "green", size = 0.5, title = "Central East Points")+

  tm_shape(south_east_points) +  
  tm_dots(col = "orange", size = 0.5, title = "South East Points")

```